p8105_jt3466_hw6
================
Johnstone Tcheou
2024-11-24

# Question 1

``` r
weather_df <-
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

    ## using cached file: C:\Users\bschn\AppData\Local/R/cache/R/rnoaa/noaa_ghcnd/USW00094728.dly

    ## date created (size, mb): 2024-09-26 10:19:43.650965 (8.668)

    ## file min/max dates: 1869-01-01 / 2024-09-30

``` r
weather_df <- 
  weather_df |> 
  modelr::bootstrap(n = 5000) |> 
  mutate(
    slr_models = map(strap, \(df) lm(tmax ~ tmin, data = df)), 
    slr_results = map(slr_models, broom::tidy),
    slr_glance = map(slr_models, broom::glance)
  ) 
```

``` r
weather_df_rsq <-
  weather_df |> 
  select(-strap, -slr_models, -slr_results) |> 
  unnest(slr_glance) |> 
  select(.id, r.squared) 

weather_df_rsq |> 
  ggplot(aes(r.squared)) +
  geom_histogram() 
```

    ## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.

![](p8105_hw6_jt3466_files/figure-gfm/q1%20r2%20distribution%20and%20ci-1.png)<!-- -->

``` r
weather_rsq_ci <-
  weather_df_rsq |>  
  summarize(
    ci_lower = quantile(r.squared, 0.025),
    ci_upper = quantile(r.squared, 0.975)
  )
```

As pictured above, with 5000 bootstrap samples, the distribution of
estimated r squared is normally distributed, with a mean estimated r
squared of 0.9115433. The 95% CI for the estimated r squared is
(0.8942627, 0.9273384). As such, `tmin` explains 91.1543252% of the
variability in `tmax`.

``` r
weather_df_log_estimates <-
  weather_df |> 
  select(-strap, -slr_models, -slr_glance) |> 
  unnest(slr_results) |> 
  select(.id, term, estimate) |> 
  group_by(.id) |> 
  mutate(
    slope = lag(estimate),
    intercept_slope = estimate*slope,
    log_intercept_slope = log10(estimate*lag(estimate))
  ) |> 
  filter(term == "tmin") |> 
  select(-term) |> 
  rename(
    intercept = estimate
  ) |> 
  pivot_longer(
    cols = intercept:log_intercept_slope,
    names_to = "terms"
  ) |> 
  filter(terms == "log_intercept_slope") |> 
  select(-terms) |> 
  rename(log_intercept_slope = value)

weather_df_log_estimates |> 
  ggplot(aes(log_intercept_slope)) +
    geom_histogram() 
```

    ## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.

![](p8105_hw6_jt3466_files/figure-gfm/q1%20log%20product%20of%20estimates-1.png)<!-- -->

``` r
weather_df_log_est_ci <-
  weather_df_log_estimates |> 
  group_by() |> 
  summarize(
    ci_lower = quantile(log_intercept_slope, 0.025),
    ci_upper = quantile(log_intercept_slope, 0.975)
  )
```

Likewise, the log base 10 of the product of the estimated intercept and
estimated slope follows an approximately normal distribution. The
average estimated log base 10 of the product of the estimated intercept
and estimated slope across the 5000 bootstrap samples is 0.8741583. The
95% CI around this estimated mean is (0.853689, 0.8943325).

# Question 2

``` r
homicide_df <- 
  read_csv(
    file = "https://raw.githubusercontent.com/washingtonpost/data-homicides/refs/heads/master/homicide-data.csv",
    na = c("Unknown", "", NA, "NA")
  ) |> 
  mutate(
    reported_date = case_match(
      reported_date,
      201511105 ~ 20151105,
      201511018 ~ 20151018,
      .default = reported_date
    ),
    reported_date = ymd(reported_date),
    city_state = paste(city, state, sep = ", "),
    solved = case_when(
      disposition == "Closed by arrest" ~ 1,
      disposition == "Closed without arrest" ~ 0,
      disposition == "Open/No arrest" ~ 0
    )
  ) |>  
  filter(!(city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", "Tulsa, AL")) & victim_race %in% c("White", "Black"))
```

    ## Rows: 52179 Columns: 12
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (8): uid, victim_last, victim_first, victim_race, victim_sex, city, stat...
    ## dbl (4): reported_date, victim_age, lat, lon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Some observations have `"Unknown"` for `victim_age`, so to catch these
in the `read_csv`, they are to be interpreted as `NA`. This way,
`victim_age` is a double variable, i.e. numeric.

``` r
baltimore_logistic <-
  homicide_df |> 
  filter(city_state == "Baltimore, MD") |> 
  glm(solved ~ victim_age + victim_sex + victim_race, data = _, family = binomial()) |> 
  broom::tidy() |> 
  mutate(
    ci_upper = estimate + 1.96 * std.error,
    ci_lower = estimate - 1.96 * std.error
  )

baltimore_logistic |> 
  filter(term == "victim_sexMale") |> 
  pull(estimate) |>  
  exp()
```

    ## [1] 0.4255117

``` r
baltimore_logistic |> 
  filter(term == "victim_sexMale") |> 
  pull(ci_lower) |>  
  exp()
```

    ## [1] 0.324559

``` r
baltimore_logistic |> 
  filter(term == "victim_sexMale") |> 
  pull(ci_upper) |> 
  exp()
```

    ## [1] 0.5578655

From this logistic regression model, the estimated odds of solving
homicides for male victims is 0.4255117 compared to female victims,
adjusting for race and age. The 95% CI for this estimated adjusted odds
ratio is (0.324559, 0.5578655).

``` r
city_or_ci <-
  homicide_df |> 
  nest(data = -city_state) |> 
  mutate(
    logistic_reg = map(data, \(df) glm(solved ~ victim_age + victim_sex + victim_race, data = df, family = binomial())),
    results = map(logistic_reg, broom::tidy)
  ) |> 
  select(-data, -logistic_reg) |> 
  unnest(results) |> 
  filter(term == "victim_sexMale") |> 
  mutate(
    or = exp(estimate),
    or_ci_lower = exp(estimate - 1.96 * std.error),
    or_ci_upper = exp(estimate + 1.96 * std.error)
  ) |> 
  select(city_state, or, or_ci_lower, or_ci_upper)
```

``` r
city_or_ci |> 
  mutate(
    city_state = fct_reorder(city_state, or)
  ) |> 
  ggplot(aes(x = city_state, y = or, fill = city_state)) +
  geom_col() +
  geom_errorbar(aes(ymin = or_ci_lower, ymax = or_ci_upper)) + 
  geom_hline(yintercept = 1.0, linetype = "dashed", color = "black") +
  theme(
    axis.text.x = element_text(angle = 90, vjust = 0.5) 
  ) +
  viridis::scale_fill_viridis(discrete = TRUE) +
  labs(
    x = "City, state",
    y = "Adjusted estimated OR of solved homicides\n for male victims compared to female victims"
  ) +
  guides(
    fill = "none"
  ) 
```

![](p8105_hw6_jt3466_files/figure-gfm/p2%20plot%20ors%20cis-1.png)<!-- -->
The estimated ORs of solved homicides for male victims compared to
female victims, adjusting for race and age, is consistently between 0
and 1 for a majority of cities, up until Atlanta, GA which has an OR of
1.0000771.

At the lower end, the ORs do not include the null value of 1 except for
Long Beach, CA, San Bernardino, CA, and a smattering of others,
including SF, Boston, MA, Sacramento, CA, Fort Worth, TX, San Antonio,
TX, and Milwaukee, WI. After this city, all of the ORs include the null
of 1.

Despite the large effect size in Albuquerque, NM, with an OR of
1.7674995, the CI is very wide and barely includes 1 with a lower end of
0.8306583. On the opposite direction, NYC has a large effect size with
0.2623978 and a CI of (0.1379459, 0.4991275). This is likely a result of
sample size - NYC has a sample size of 412, while Albuquerque has a
sample size of 178, less than half the sample size in NYC.

# Question 3

``` r
birthweight_df <- 
  read_csv(
    file = "https://p8105.com/data/birthweight.csv",
    na = c("", ".", "NA", NA)
  ) |> 
  janitor::clean_names() |>
  mutate(
    babysex = 
        case_match(babysex,
            1 ~ "male",
            2 ~ "female"
        ),
    babysex = fct_infreq(babysex),
    frace = 
        case_match(frace,
            1 ~ "white",
            2 ~ "black", 
            3 ~ "asian", 
            4 ~ "puerto rican", 
            8 ~ "other"),
    frace = fct_infreq(frace),
    mrace = 
        case_match(mrace,
            1 ~ "white",
            2 ~ "black", 
            3 ~ "asian", 
            4 ~ "puerto rican",
            8 ~ "other"),
    mrace = fct_infreq(mrace),
    malform = as.logical(malform),
    id = row_number()
  ) 
```

    ## Rows: 4342 Columns: 20
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (20): babysex, bhead, blength, bwt, delwt, fincome, frace, gaweeks, malf...
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
birthweight_df |> 
  filter(is.na(bwt))
```

    ## # A tibble: 0 × 21
    ## # ℹ 21 variables: babysex <fct>, bhead <dbl>, blength <dbl>, bwt <dbl>,
    ## #   delwt <dbl>, fincome <dbl>, frace <fct>, gaweeks <dbl>, malform <lgl>,
    ## #   menarche <dbl>, mheight <dbl>, momage <dbl>, mrace <fct>, parity <dbl>,
    ## #   pnumlbw <dbl>, pnumsga <dbl>, ppbmi <dbl>, ppwt <dbl>, smoken <dbl>,
    ## #   wtgain <dbl>, id <int>

``` r
summary(birthweight_df)
```

    ##    babysex         bhead          blength           bwt           delwt      
    ##  male  :2230   Min.   :21.00   Min.   :20.00   Min.   : 595   Min.   : 86.0  
    ##  female:2112   1st Qu.:33.00   1st Qu.:48.00   1st Qu.:2807   1st Qu.:131.0  
    ##                Median :34.00   Median :50.00   Median :3132   Median :143.0  
    ##                Mean   :33.65   Mean   :49.75   Mean   :3114   Mean   :145.6  
    ##                3rd Qu.:35.00   3rd Qu.:51.00   3rd Qu.:3459   3rd Qu.:157.0  
    ##                Max.   :41.00   Max.   :63.00   Max.   :4791   Max.   :334.0  
    ##     fincome               frace         gaweeks       malform       
    ##  Min.   : 0.00   white       :2123   Min.   :17.70   Mode :logical  
    ##  1st Qu.:25.00   black       :1911   1st Qu.:38.30   FALSE:4327     
    ##  Median :35.00   puerto rican: 248   Median :39.90   TRUE :15       
    ##  Mean   :44.11   asian       :  46   Mean   :39.43                  
    ##  3rd Qu.:65.00   other       :  14   3rd Qu.:41.10                  
    ##  Max.   :96.00                       Max.   :51.30                  
    ##     menarche        mheight          momage              mrace     
    ##  Min.   : 0.00   Min.   :48.00   Min.   :12.0   white       :2147  
    ##  1st Qu.:12.00   1st Qu.:62.00   1st Qu.:18.0   black       :1909  
    ##  Median :12.00   Median :63.00   Median :20.0   puerto rican: 243  
    ##  Mean   :12.51   Mean   :63.49   Mean   :20.3   asian       :  43  
    ##  3rd Qu.:13.00   3rd Qu.:65.00   3rd Qu.:22.0                      
    ##  Max.   :19.00   Max.   :77.00   Max.   :44.0                      
    ##      parity            pnumlbw     pnumsga      ppbmi            ppwt      
    ##  Min.   :0.000000   Min.   :0   Min.   :0   Min.   :13.07   Min.   : 70.0  
    ##  1st Qu.:0.000000   1st Qu.:0   1st Qu.:0   1st Qu.:19.53   1st Qu.:110.0  
    ##  Median :0.000000   Median :0   Median :0   Median :21.03   Median :120.0  
    ##  Mean   :0.002303   Mean   :0   Mean   :0   Mean   :21.57   Mean   :123.5  
    ##  3rd Qu.:0.000000   3rd Qu.:0   3rd Qu.:0   3rd Qu.:22.91   3rd Qu.:134.0  
    ##  Max.   :6.000000   Max.   :0   Max.   :0   Max.   :46.10   Max.   :287.0  
    ##      smoken           wtgain             id      
    ##  Min.   : 0.000   Min.   :-46.00   Min.   :   1  
    ##  1st Qu.: 0.000   1st Qu.: 15.00   1st Qu.:1086  
    ##  Median : 0.000   Median : 22.00   Median :2172  
    ##  Mean   : 4.145   Mean   : 22.08   Mean   :2172  
    ##  3rd Qu.: 5.000   3rd Qu.: 28.00   3rd Qu.:3257  
    ##  Max.   :60.000   Max.   : 89.00   Max.   :4342

``` r
birthweight_df |> 
  select(id, bwt) |> 
  ggplot(aes(x = bwt)) +
  geom_histogram()
```

    ## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.

![](p8105_hw6_jt3466_files/figure-gfm/p3%20eda-1.png)<!-- -->

``` r
birthweight_df |> 
  select(id, wtgain) |> 
  ggplot(aes(x = wtgain)) +
  geom_histogram()
```

    ## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.

![](p8105_hw6_jt3466_files/figure-gfm/p3%20eda-2.png)<!-- -->

``` r
birthweight_df |> 
  ggplot(aes(x = babysex, y = bwt, fill = babysex)) +
  geom_boxplot()
```

![](p8105_hw6_jt3466_files/figure-gfm/p3%20eda-3.png)<!-- -->

``` r
birthweight_df |> 
  ggplot(aes(x = babysex, y = bwt, fill = babysex)) +
  geom_boxplot() +
  facet_wrap(~mrace)
```

![](p8105_hw6_jt3466_files/figure-gfm/p3%20eda-4.png)<!-- -->

``` r
birthweight_df |> 
  ggplot(aes(x = babysex, y = bwt, fill = babysex)) +
  geom_boxplot() +
  facet_wrap(~frace)
```

![](p8105_hw6_jt3466_files/figure-gfm/p3%20eda-5.png)<!-- -->

``` r
birthweight_df |> 
  ggplot(aes(x = babysex, y = bwt, fill = babysex)) +
  geom_boxplot() +
  facet_wrap(~malform)
```

![](p8105_hw6_jt3466_files/figure-gfm/p3%20eda-6.png)<!-- -->

``` r
birthweight_df |> 
  ggplot(aes(x = parity, y = bwt, color = parity)) + 
  geom_point()
```

![](p8105_hw6_jt3466_files/figure-gfm/p3%20eda-7.png)<!-- -->

``` r
birthweight_df |> 
  group_by(parity) |> 
  summarize(
    count = n()
  ) # small sample size
```

    ## # A tibble: 4 × 2
    ##   parity count
    ##    <dbl> <int>
    ## 1      0  4339
    ## 2      1     1
    ## 3      3     1
    ## 4      6     1

``` r
birthweight_df |> 
  ggplot(aes(x = pnumlbw, y = bwt, color = pnumlbw)) + 
    geom_point()
```

![](p8105_hw6_jt3466_files/figure-gfm/p3%20eda-8.png)<!-- -->

``` r
birthweight_df |> 
  group_by(pnumlbw) |> 
  summarize(
    count = n()
  )
```

    ## # A tibble: 1 × 2
    ##   pnumlbw count
    ##     <dbl> <int>
    ## 1       0  4342

``` r
birthweight_df |> 
  group_by(pnumsga) |> 
  summarize(
    count = n()
  )
```

    ## # A tibble: 1 × 2
    ##   pnumsga count
    ##     <dbl> <int>
    ## 1       0  4342

``` r
birthweight_df |> 
  ggplot(aes(x = wtgain, y = bwt)) +
  geom_point(alpha = 0.5) +
  geom_smooth(stat = "smooth", se = FALSE)
```

    ## `geom_smooth()` using method = 'gam' and formula = 'y ~ s(x, bs = "cs")'

![](p8105_hw6_jt3466_files/figure-gfm/p3%20eda-9.png)<!-- -->

``` r
birthweight_df |> 
  ggplot(aes(x = ppwt, y = bwt)) +
  geom_point(alpha = 0.5) +
  geom_smooth(stat = "smooth", se = FALSE)
```

    ## `geom_smooth()` using method = 'gam' and formula = 'y ~ s(x, bs = "cs")'

![](p8105_hw6_jt3466_files/figure-gfm/p3%20eda-10.png)<!-- -->

``` r
birthweight_df |> 
  ggplot(aes(x = ppbmi, y = bwt)) +
  geom_point(alpha = 0.5) +
  geom_smooth(stat = "smooth", se = FALSE)
```

    ## `geom_smooth()` using method = 'gam' and formula = 'y ~ s(x, bs = "cs")'

![](p8105_hw6_jt3466_files/figure-gfm/p3%20eda-11.png)<!-- -->

``` r
birthweight_df |> 
  ggplot(aes(x = delwt, y = bwt)) +
  geom_point(alpha = 0.5) +
  geom_smooth(stat = "smooth", se = FALSE)
```

    ## `geom_smooth()` using method = 'gam' and formula = 'y ~ s(x, bs = "cs")'

![](p8105_hw6_jt3466_files/figure-gfm/p3%20eda-12.png)<!-- -->

``` r
birthweight_df |> 
  ggplot(aes(x = fincome, y = bwt)) +
  geom_point(alpha = 0.5) +
  geom_smooth(stat = "smooth", se = FALSE)
```

    ## `geom_smooth()` using method = 'gam' and formula = 'y ~ s(x, bs = "cs")'

![](p8105_hw6_jt3466_files/figure-gfm/p3%20eda-13.png)<!-- -->

``` r
birthweight_df |> 
  ggplot(aes(x = momage, y = bwt)) +
  geom_point(alpha = 0.5) +
  geom_smooth(stat = "smooth", se = FALSE)
```

    ## `geom_smooth()` using method = 'gam' and formula = 'y ~ s(x, bs = "cs")'

![](p8105_hw6_jt3466_files/figure-gfm/p3%20eda-14.png)<!-- -->

``` r
birthweight_df |> 
  ggplot(aes(x = smoken, y = bwt)) +
  geom_point(alpha = 0.5) +
  geom_smooth(stat = "smooth", se = FALSE)
```

    ## `geom_smooth()` using method = 'gam' and formula = 'y ~ s(x, bs = "cs")'

![](p8105_hw6_jt3466_files/figure-gfm/p3%20eda-15.png)<!-- --> In
exploring the data, the outcome of interest, birthweight (`bwt`) in
grams, is approximately normally distributed, though it has a left skew.
The median is at 3132.5 g, with a mean of 3114.4039613 g, a max of 4791
g, and a min of 595 g.

Based on these visualizations to explore possible associations with
potential predictors and birthweight, `mrace` does seem to have an
effect on the median birthweight, with Puerto Rican and Asian mothers
having a similar median birthweight as White mothers, while Black
mothers have a lower median birthweight. For paternal race, there is
more variation in its effect on median birthweight. As before Black
fathers have a lower median birthweight compared to fathers of other
races, but there also seems to be a slightly lower median birthweight
for female babies compared to male babies for White, Black, and Puerto
Rican fathers.

Interestingly, the presence of malformations that could affect weight
has a disproportionately greater effect among female babies than male
babies, though even babies without malformations display a disparity in
median birthweight, with female babies still having a lower median
birthweight. The median birthweight for male babies appears the same for
those with and without malformations.

For maternal characteristics, parity is predominately 0 for most
subjects with a few having more than 0 prior births, so it would not be
an insightful covariate to include. No mothers had prior low birth
weight babies nor prior small for gestational age babies, making them
likewise unimportant covariates.

Potential predictors of these maternal characteristics for birthweight
could include weight gain, prepregnancy weight, and especially weight at
delivery. These covariates show an approximately linear relation with
increasing weight gain and weight at these stages approximating to an
increase in birthweight. However, the relationship between maternal
weight at delivery and birthweight is somewhat parabolic, suggesting it
may be best explained by a quadratic term instead.

Number of cigarettes smoked has a less steep relationship with
birthweight but broadly shows more cigarettes smoked is associated with
lower birthweight babies. Maternal income has the opposite magnitude
relationship, with higher birthweight associated with higher maternal
income. Maternal age also has a parabolic relationship, with lower
birthweight at the extreme ends of below 15 and above 35 years old.

Based on these, to best predict birthweight, a variety of baby
characteristics and maternal characteristics (physical, social, and
behavioral) were selected as covariates based on the approximate
magnitude of their relationship with birthweight, in favor over
parsimony. `babysex` is a particularly important variable to include,
given that female babies appear disproportionately affected by some of
these covariates, like malformations and parental race. As such, the
interactions of baby sex and parental races were included. However,
given the main difference in birthweight was seen for Black parents,
`frace` and `mrace` were recategorized to be binary Black or
White/Asian/Puerto Rican/Other. Other factor variables were releveled to
ensure the correct reference group is selected when running the model.

``` r
birthweight_df <-
  birthweight_df |> 
  mutate(
    frace = as.character(frace),
    frace = 
        case_match(frace,
            "white" ~ "white",
            "black" ~ "non white", 
            "asian" ~ "non white", 
            "puerto rican" ~ "non white", 
            "other" ~ "non white"),
    frace = fct_relevel(frace, "non white", "white"),
    mrace = as.character(mrace),
    mrace = 
        case_match(mrace,
            "white" ~ "white",
            "black" ~ "non white", 
            "asian" ~ "non white", 
            "puerto rican" ~ "non white", 
            "other" ~ "non white"),
    mrace = fct_relevel(frace, "non white", "white"),
    babysex = as.factor(babysex),
    babysex = fct_relevel(babysex, "female", "male")
  )


bwt_model <- lm(bwt ~ babysex + mrace + frace + malform + wtgain + ppwt + I(delwt^2) + fincome + I(momage^2) + babysex*mrace + babysex*frace, data = birthweight_df) |> 
  broom::tidy()
```

However, paternal race was estimated as `NA`, indicating collinearity
with the other predictors, so it and its interaction term with baby sex
should be removed. The interaction term of baby sex and maternal race is
also not significant, so it is likewise removed.

``` r
bwt_model <- lm(bwt ~ babysex + mrace + malform + wtgain + ppwt + I(delwt^2) + fincome + I(momage^2), data = birthweight_df)

bwt_model |> 
  broom::tidy() |> 
  knitr::kable(digits = 3)
```

| term        | estimate | std.error | statistic | p.value |
|:------------|---------:|----------:|----------:|--------:|
| (Intercept) | 1000.460 |   176.164 |     5.679 |   0.000 |
| babysexmale |   69.022 |    13.987 |     4.935 |   0.000 |
| mracewhite  |  258.523 |    15.544 |    16.631 |   0.000 |
| malformTRUE | -136.890 |   119.078 |    -1.150 |   0.250 |
| wtgain      |   24.877 |     2.239 |    11.112 |   0.000 |
| ppwt        |   18.012 |     2.232 |     8.068 |   0.000 |
| I(delwt^2)  |   -0.041 |     0.007 |    -5.941 |   0.000 |
| fincome     |    0.644 |     0.300 |     2.147 |   0.032 |
| I(momage^2) |    0.091 |     0.042 |     2.161 |   0.031 |

``` r
rvf <-
  birthweight_df |> 
  modelr::add_residuals(bwt_model) |> 
  modelr::add_predictions(bwt_model)

rvf |> 
  ggplot(aes(x = pred, y = resid)) +
  geom_point() +
  geom_hline(yintercept = 0.0, linetype = "dashed", color = "black") +
  labs(
    title = "Residuals vs fitted values for birthweight", 
    xlab = "Fitted values",
    ylab = "Residuals"
  )
```

![](p8105_hw6_jt3466_files/figure-gfm/rvf%20plot-1.png)<!-- -->

Based on the residuals vs fitted plot, we see that the residuals have
equal variance around the e = 0 line as there is no fanning of
homoscedasticity violations. Therefore, the error terms maintain
homoscedasticity at all fitted values.

``` r
bwt_cv_df <-
  modelr::crossv_mc(birthweight_df, 100) |> 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble)
  ) 

bwt_cv_df <-
  bwt_cv_df |> 
  mutate(
    jt_model = map(train, \(df) lm(bwt ~ babysex + mrace + malform + wtgain + ppwt + I(delwt^2) + fincome + I(momage^2), data = df)),
    main_fx_model = map(train, \(df) lm(bwt ~ blength + gaweeks, data = df)),
    interaction_model = map(train, \(df) lm(bwt ~ bhead + blength + babysex + bhead*blength + bhead*babysex + blength*babysex + bhead*blength*babysex, data = df))
  ) |> 
  mutate(
    rmse_jt = map2_dbl(jt_model, test, \(model, df) modelr::rmse(model = model, data = df)),
    rmse_main = map2_dbl(main_fx_model, test, \(model, df) modelr::rmse(model = model, data = df)),
    rmse_interaction = map2_dbl(interaction_model, test, \(model, df) modelr::rmse(model = model, data = df))
  )
```

``` r
bwt_cv_df |> 
  select(starts_with("rmse")) |> 
  pivot_longer(
    everything(), 
    names_to = "model", 
    values_to = "rmse",
    names_prefix = "rmse_"
  ) |> 
  mutate(
    model = as_factor(model),
    model = fct_reorder(model, rmse)
  ) |> 
  ggplot(aes(x = model, y = rmse, fill = model)) +
  geom_violin() +
  stat_summary(fun = "median", geom = "point", color = "black") +
  guides(
    fill = "none"
  )
```

![](p8105_hw6_jt3466_files/figure-gfm/rmse%20plot-1.png)<!-- -->

``` r
bwt_cv_df |> 
  select(starts_with("rmse")) |> 
  pivot_longer(
    everything(), 
    names_to = "model", 
    values_to = "rmse",
    names_prefix = "rmse_"
  ) |> 
  group_by(model) |> 
  summarize(avg_rmse = mean(rmse)) |> 
  arrange(avg_rmse)
```

    ## # A tibble: 3 × 2
    ##   model       avg_rmse
    ##   <chr>          <dbl>
    ## 1 interaction     289.
    ## 2 main            332.
    ## 3 jt              461.

My model has much higher root mean squared errors compared to the other
two models of just the main effects of length at birth and gestational
age and the main effects of head circumference, length, sex, and all
their interactions. My model focuses more on potential parental
predictors than baby covariates, suggesting models that account for baby
characteristics like length, head circumference, etc, and especially
their interactions, may be better at predicting birthweight than models
with parental covariates like my model.
